version: '2'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_1234789
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql:rw
    ports:
      - 3306:33060
  wordpress:
    depends_on:
      - db
    build:
      context: ./wp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: my_database
    volumes:
      - ./wp:/var/www/html:rw
  
  gatsby:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/:/app/ 
      - /app/node_modules
    ports:
      - "3000:3000"